ADDITION OF SECTION AND ABOUT PAGE ON MY MOBILE PORTFOLIO
citec-47/Mobile-view pull request #1
Opened 2023-02-16 13:58 UTC by citec-47

#ADDITION OF SECTION AND ABOUT PAGE ✔✔✔
# SET-UP✔✔
#General requirements🧾
-Make sure that there are [no linter errors] (https://github.com/microverseinc/linters-config):
-Linter should be set up correctly for this repository.
-Linter result should be green.
-There should be no custom changes to linter config.
*Make sure that you used correct [GitHub Flow] (https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git--github/articles/github_flow.md):
-README file should be descriptive.
-Commit messages should be meaningful.
*Pull Request should have a descriptive title telling you what changes are inside.
-Pull Request should have a short summary describing introduced changes in more detail.
-Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal skills/blob/main/documentation/articles/professional_repo_rules.md):
-Branch should describe a feature or action (e.g. 'created_sidebar' or 'added_comments_section').
-Pull Request is made from 'feature branch' into the main branch.
HTML/CSS requirements🧾🌳
-Follow our list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
-Project requirements
-IMPORTANT NOTE: For each Microverse project, you need to create a separate pull request. It is the first time you need to work with multiple pull requests in your one repository. [Read how to do it most efficiently](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/multiple_pull_requests.md).

🧾Now you will build the middle section of the mobile website. We included a screenshot of Template 1 below for reference, but you should stick to the template that you chose. This sections of the mobile website should include:

#"Works" section
-Toolbar

-the "About myself" section (placed after the projects and before the contact form):
-About myself

-Make sure the content of the "About myself" section is aligned with flexbox.

-In order to lay out the elements in "Works" section you should use CSS Grid and Flexbox combined (it is mandatory that you use both). Use CSS Grid in the main container that contains all of the cards and use Flexbox to lay out an individual card.

-Please use ul and li for categories in "Work" section. Html, CSS, and JavaScript should be list items.

-Please use ul and li for categories in "About myself" section. Languages, Frameworks, and Skills should be list items.

-You don't need to implement the detail modal window that requires JavaScript.

-You must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

Implement the button interactions (enable, hover, etc.).

2023-02-16 16:40 UTC, ABDULALI3468 requested changes
# Changes Required 👍 

Hi @citec-47 , 

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

 Indeed you did an exceptional job but still, there are a few things that need to be addressed to go to the next level.


## Highlights 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.


 ## Required Changes ♻️

> **_Check the comments below to have a look at the required changes._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 16:40 UTC, ABDULALI3468 commented on index.html
> +<section>
Please consider using `display: grid;` for the container to align the elements as its a project requirement.

2023-02-16 16:40 UTC, ABDULALI3468 commented on index.html
> +  </div>
Currently, your styles are not exactly lookalike to the Figme design template you have chosen. Remember your style needs to be like a template at least above 375px until it hits desktop size. Currently, they are not as it's flowing out of their container height. I am attaching a screenshot of your design to make it more clear. 

## Your Design:-

![image](https://user-images.githubusercontent.com/94223367/219420165-741670c1-cb7d-4dd8-8bb7-72ca90553994.png)

2023-02-16 16:40 UTC, ABDULALI3468 commented on index.html
> +          <a href="https://www.facebook.com/ndonyi.maurice" class="resume">See Project</a>
Please consider adding the functionality of press on the button. So when the button is pressed its style changes as follows. To achieve this you can add the following functionality of code into your CSS file.

.resume:active{
    background-color: #2230D2;
    color: white;
}

![image](https://user-images.githubusercontent.com/94223367/219416172-4958d9ca-1fa4-4068-adbb-ef3657bc7b3f.png)

2023-02-16 16:40 UTC, ABDULALI3468 commented on index.html
> +      <button class="resume">Get my resume</button>
Please consider adding the functionality of press on the button. So when the button is pressed its style changes as follows. To achieve this you can add the following functionality of code into your CSS file.

.resume:active{
    background-color: #2230D2;
    color: white;
}

![image](https://user-images.githubusercontent.com/94223367/219416172-4958d9ca-1fa4-4068-adbb-ef3657bc7b3f.png)

2023-02-16 16:40 UTC, ABDULALI3468 commented on index.html
> +  </section>
Please consider following these 2 rules in this section as it's a good practice for semantics:-

1. The technology categories ("Languages", "Frameworks" and "Skills") are in a `ul`, each of them in a `li`
2. The technology in each category(e.g., "JavasScript", "HTML" and "CSS") are also a list `ul` and each of them a `li`

Following is the code representation of the above if you are confused about what the instructions mean:-


`    <ul>
      <li>
        Languages
        <ul>
          <li>JavaScript</li>
          <li>Python</li>
          <li>Java</li>
        </ul>
      </li>
      <li>Frameworks</li>
      <li>Skills</li>
    </ul>`


![image](https://user-images.githubusercontent.com/94223367/219422805-c6dd3bc7-bbc1-4dba-9c18-85bc5d823350.png)

2023-02-16 16:40 UTC, ABDULALI3468 commented on index.html
> +<section class="about_me">
Please consider reconsidering your design to match the Figma template. It includes similar margins in this case etc. Moreover, on the right side of Languages, there needs to be an icon that is not showing consider rechecking it.

2023-02-17 04:07 UTC, citec-47 commented
#CHANGES REQUIRED🌳
-Addition of the hover effects✔
-adding display grid on the contact-list section✔
-using ul instead of div on the about section✔
-making sure the minimum width should be 375px as prescribe for the exercise✔

2023-02-17 04:59 UTC, AbayomiOlaoye approved these changes
Hi @citec-47 :clap: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![applause](https://user-images.githubusercontent.com/99715640/213818870-485b6c36-1d87-4b93-9a0c-ce2ae86d9a9d.gif)

## Highlights
- Great implementation of reviewer's suggestions :heavy_check_mark: 
- Good UI implementation :heavy_check_mark: 
- Linter checks are passing :heavy_check_mark: 

## Optional suggestions

_N/A_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 05:14 UTC, merged